### ISSUE TITLE
E5108: Error executing lua ....cache/init.vim/.dein/lua/libmodal/src/utils/api.lua:82: Vim(echon):E121: Undefined variable: char

### ISSUE THREAD

**Issue by galou** [Iron-E/nvim-tabmode#2] opened 2020-07-02 08:02 UTC
This happens when I press the `left`, `right` key or `<Ctrl+PgUp>` or `<Ctrl+PgDown>`.

**Comment by Iron-E** [comment] 2020-07-02 16:21
Thanks for the bug report! I use this plugin every day so I was pretty confident it was bug-free, come to find out two bugs were discovered within 24 hours of each other is quite the surprise. I'm glad you caught them!

I can confirm this issue is present on Neovim 0.4.3+. This seems to be caused by the fact that `nvim-libmodal` (and `vim-libmodal`, for that matter) report user input as a character number (since some special characters such as `^M` must be handled). After handling special cases I use (and have recommended in documentation that) `string.char()` in Lua be used to revert the character number back into a character. but

However, `<Left>` and `<Right>` convert back to `<80>kl` and `<80>kr` respectively. These can't be converted back to characters using `string.char()`. Luckily this seems to be an easy fix thanks to the `getchar()` help page.

**Comment by Iron-E** [comment] 2020-07-02 16:22
I have updated `bugfix/1.0.2` to include a fix for this issue as well. Let me know if it works for you, and I will merge it into master long with the fix for #1

**Comment by galou** [comment] 2020-07-03 08:01
I'm probably not a Vim guru yet because I dared using the arrow keys!

`fix/1.0.2` now solves the issue. `<Left>` and `<Right>` work perfectly. `<Ctrl+PgUp>` and `<Ctrl+PgDown>` don't do anything but they don't throw any error neither.

Thanks a lot! And that was blazing fast!

**Comment by Iron-E** [comment] 2020-07-03 16:27
Glad it works for you and that I was able to get it done in a reasonable time table!

I never implemented behavior for `<Ctrl+PgUp>` or `<Ctrl+PgDown>`. What behavior did you expect? I can add it with another commit.

**Closed as completed** 2020-07-03 16:28 UTC
Labels: bug

**Comment by galou** [comment] 2020-07-06 06:55
`<Ctrl-PgUp>` and `<Ctrl-PgDown>` switch to the next/previous tab (I don't think I changed the configuration for these bindings).
